## Works fine but a little costly for a microscopic project.
#
#name: Build
#
#on: push
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2.3.4
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v1.2.1
#      - name: Setup gcloud
#        uses: google-github-actions/setup-gcloud@v0.2.0
#        with:
#          service_account_key: ${{ secrets.GAUP_GOOGLE_SA_KEY }}
#          project_id: deknijf-gaup
#          export_default_credentials: true
#      - run: terraform init -input=false
#        working-directory: terraform
#      - run: terraform apply -auto-approve -input=false
#        working-directory: terraform
#        env:
#          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#      - run: gsutil cp src/* gs://deknijf-gaup/
